### ISSUE TITLE
Update README for Improved Documentation

### ISSUE THREAD

**Issue by jinx-vi-0** [open-xyz/xmail#20]
The current README is not visually appealing and also lacks some sections like how to make pr, contributors, etc. I would also like to update readme and also properly format the documentation.

![image](https://github.com/open-xyz/xmail/assets/120160355/6c767dab-1b30-49fb-b879-fe7da81fcd06)

**Comment by rohansx** [comment]
@jinx-vi-0 I don't think it's a good idea to add 'how to make a PR' in the README file, since the contributing.md file is specifically for that purpose.
What other improvements can you suggest for the README file?

**Comment by jinx-vi-0** [comment]
@rohansx ok so I can improve its formatting like add badges for tech stacks, repo stats counts and include contributors at the bottom of readme.

**Comment by sesiii** [comment]
Can someone explain what is the project about?
What do we need to build?
